toptier_gaming/account/urls.py
from django.urls import path
from . import views


app_name = "account"

urlpatterns = [
    path('login/', views.user_login, name="login")
]

toptier_gaming/teamlink/urls.py
from django.urls import path
from . import views


app_name = "teamlink"
urlpatterns = [
    path('', views.team_post_list, name="team_post_list"),
    path("<int:id>/", views.team_post_detail, name="team_post_detail"),
]

toptier_gaming/toptier_gaming/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teamlink/', include('teamlink.urls', namespace="teamlink")),
]

toptier_gaming/account/models.py
from django.db import models

# Create your models here.

toptier_gaming/teamlink/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=TeamPost.Status.PUBLISHED)


class TeamPost(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', "Draft"
        PUBLISHED = 'PU', 'Published'
        
    class Visibility(models.TextChoices):
        ORG = "OR", "Org Internal"
        ROSTER = "RO", "Roster Internal"
        PUBLIC = "PU", "Publically Visible"
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="team_posts"
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    visibility = models.CharField(max_length=2, choices=Visibility.choices, default=Visibility.PUBLIC)
    objects = models.Manager()
    published = PublishedManager() 
    
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
    
    def __str__(self):
        return self.title

toptier_gaming/account/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    

toptier_gaming/account/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm
# Create your views here.


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password']
            )
            if user is not None:
                login(request, user)
                return HttpResponse("Authenticated Successfully.")
            else:
                return HttpResponse("Invalid Credentials")
                
    else:
        form = LoginForm()
    return render(
        request,
        'account/login.html',
        {'form': form}
    )

toptier_gaming/teamlink/views.py
from django.shortcuts import render, get_object_or_404
from .models import TeamPost

# Create your views here.
def team_post_list(request):
    team_posts = TeamPost.published.all()
    return render(
        request,
        'teamlink/team_post/list.html',
        {'team_posts': team_posts}
    )


def team_post_detail(request, id):
    team_post = get_object_or_404(
        TeamPost,
        id=id,
        status=TeamPost.Status.PUBLISHED
    )
    return render(
        request,
        'teamlink/team_post/detail.html',
        {'team_post': team_post}
    )

toptier_gaming/teamlink/templates/teamlink/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/teamlink.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div id="sidebar">
            <h2>Team Link</h2>
            <p>Welcome to the teamlink bulletin!</p>
        </div>
    </body>
</html>

toptier_gaming/teamlink/templates/teamlink/team_post/list.html
{% extends "teamlink/base.html" %}
{% block title %}Teamlink{% endblock %}
{% block content %}
    <h1>Teamlink</h1>
    {% for team_post in team_posts %}
    <h2>
        <a href="{% url 'teamlink:team_post_detail' team_post.id %}">
            {{ team_post.title }}
        </a>
    </h2>
    <p class="date">
        Published {{ team_post.publish }} by {{team_post.author }}
    </p>
    {{ team_post.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% endblock %}